# Generated by Django 4.1.2 on 2023-01-02 08:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='monthly_payment',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
